### ISSUE TITLE
cache system not senstitive to changing backends

### ISSUE THREAD

**Issue by chick** [ucb-sejits/ctree#41]
problem: stencil examples will create two stencils of the same type but whose backend is different. Caching will retrieve files from the first stencil instantiated thinking they are a hit for a stencil with a different backend

**Comment by leonardt** [comment]
Solution, include backend in the program configuration (require a field or method self.backend that returns the current backend).

That way if the backend changes the configuration changes and it incurs a cache miss.

**Comment by chick** [comment]
I don't think this is going to get fixed.
