### ISSUE TITLE
Travis builds failing, can't install opencl headers

### ISSUE THREAD

**Issue by chick** [ucb-sejits/ctree#49]
$ sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers
E: Version '2:8.960-0ubuntu1' for 'fglrx' was not found

**Comment by leonardt** [comment]
fglrx was installed to get OpenCL.  Removing the version specifier will probably be okay, but if not [this repo](https://github.com/JuliaGPU/OpenCL.jl/blob/master/.travis.yml) installs OpenCL from scratch on Travis

**Comment by chick** [comment]
Thanks Lenny, I figured it was something like this but had not explored it
yet.
Good to hear from you, how's it going?
-chick

Chick Markley
Staff Programmer -- Aspire Lab
University of California, Berkeley
583-2 Soda Hall, Berkeley, CA 94720-1776
chick@berkeley.edu

**Comment by chick** [comment]
Not going to fix at this time.
