### ISSUE TITLE
Ctree code generation from C code

### ISSUE THREAD

**Issue by vandana96** [ucb-sejits/ctree#54]
Hello,

Is there any mechanism through which Ctree code can be generated from a C Code?

Example:
input C Code:
#pragma omp parallel for
for(int c0 = 0; c0 <= 199; c0=c0+1)
{
      #pragma omp parallel for
      for(int c1 = c0; c1 <= c0; c1 = c1+1)
      {
             Statement
      }
}

Expected output:
ast = CFile("test", [OmpParallelFor(),
                     For(Assign(SymbolRef("c0", c_int()), Constant(0)),
                         LtE(SymbolRef("c0"), Constant(199)),
                         Assign(SymbolRef("c0"), Add(SymbolRef("c0"), Constant(1))),
                         [OmpParallelFor(),
                          For(Assign(SymbolRef("c1", c_int()), SymbolRef("c0")),
                              LtE(SymbolRef("c1"), Add(SymbolRef("c0"), Constant(99))),
                              Assign(SymbolRef("c1"), Add(SymbolRef("c1"), Constant(1))),
                                   [SymbolRef("Statement")])])])

Regards.

**Comment by chick** [comment]
I don't think there is a way to do this.  Also, the Ctree library is no longer under active development, so it's probably not going to be easy to get a lot of support for this.

**Comment by mbdriscoll** [comment]
@chick is correct. Your best bet for C AST manipulation in Python is pycparser, but it might not support OpenMP pragmas. The ROSE Compiler is also good if you want support for C->C translation.

**Comment by vandana96** [comment]
Thank you.
